In [2]:
from sklearn import preprocessing

In [10]:
weather=["Sunny","Sunny","Overcast","Rainy","Rainy","Rainy","Overcast","Sunny","Sunny","Rainy","Sunny","Overcast","Overcast","Rainy"]

temp=["hot","hot","hot","mild","cool","cool","cool","mild","cool","mild","mild","mild","hot","mild"]

play=["No","No","Yes","yes","yes","No","yes","No","yes","yes","yes","yes","yes","No"]

In [11]:
le=preprocessing.LabelEncoder()

In [12]:
weather_encoder=le.fit_transform(weather)
print(weather_encoder)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [13]:
temp_encoder=le.fit_transform(temp)
print(temp_encoder)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [14]:
play_encoder=le.fit_transform(play)
print(play_encoder)

[0 0 1 2 2 0 2 0 2 2 2 2 2 0]


In [21]:
label=le.fit_transform(play)

feature=list(zip(weather_encoder,temp_encoder))
print(feature)

[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]


In [22]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=3)
model.fit(feature,label)

KNeighborsClassifier(n_neighbors=3)

In [25]:
predicted=model.predict([[0,2]])
predicted

array([2], dtype=int64)

In [26]:
from sklearn import datasets

In [29]:
wine=datasets.load_wine()
print(wine.feature_names)
print(wine.target_names)
print(wine.data[0,5])

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']
2.8


In [31]:
print(wine.data.shape)

(178, 13)


In [32]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.3)

In [42]:
knn=KNeighborsClassifier(n_neighbors=5)

In [43]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [44]:
y_pred=knn.predict(x_test)
print(y_pred)

[2 2 2 0 0 0 1 2 0 0 2 0 2 2 2 1 2 2 1 1 0 1 1 1 2 1 0 0 2 0 2 0 1 0 2 0 0
 2 1 1 1 0 2 0 0 1 0 2 2 0 1 1 1 2]


In [45]:
from sklearn import metrics

In [46]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.7222222222222222


In [47]:
x_train,x_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.3)

In [48]:
knn=KNeighborsClassifier(n_neighbors=7)

In [49]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [50]:
y_pred=knn.predict(x_test)
print(y_pred)

[0 0 0 2 0 1 0 0 2 2 0 2 0 1 1 1 0 0 1 0 0 1 2 1 1 2 0 1 0 0 1 1 0 0 2 1 1
 1 1 0 2 1 2 1 1 2 2 0 2 0 1 0 2 1]


In [51]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.6666666666666666


In [62]:
x_train,x_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.25)

In [63]:
knn=KNeighborsClassifier(n_neighbors=7)

In [64]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [65]:
y_pred=knn.predict(x_test)
print(y_pred)

[2 1 0 1 0 1 2 0 0 2 2 1 0 2 2 2 2 0 2 0 2 0 2 1 0 2 2 2 1 0 1 0 2 0 0 1 2
 1 0 1 1 1 1 0 2]


In [66]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.7111111111111111


In [67]:
knn=KNeighborsClassifier(n_neighbors=9)

In [68]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [59]:
y_pred=knn.predict(x_test)
print(y_pred)

[0 2 0 2 1 1 1 2 1 1 1 1 0 1 1 0 2 2 2 2 1 2 0 2 0 2 0 1 1 1 2 1 1 0 0 0 1
 0 1 0 0 2 1 2 0 2 1 0 1 1 0 1 1 2]


In [60]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.7592592592592593


In [61]:
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print(y_pred)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

[0 2 0 2 1 1 1 2 1 1 1 1 0 1 1 0 2 2 2 2 1 2 0 2 0 2 0 1 1 1 2 1 1 0 0 0 1
 0 1 0 0 2 1 2 0 2 1 0 1 1 0 1 1 2]
Accuracy: 0.7592592592592593


In [74]:
import pandas as pd
df=pd.read_csv("IS Lab Datasets/Lab5_penguins.csv")
df

Unnamed: 0    species     island  bill_length_mm  bill_depth_mm  \
0             1     Adelie  Torgersen            39.1           18.7   
1             2     Adelie  Torgersen            39.5           17.4   
2             3     Adelie  Torgersen            40.3           18.0   
3             4     Adelie  Torgersen             NaN            NaN   
4             5     Adelie  Torgersen            36.7           19.3   
..          ...        ...        ...             ...            ...   
339         340  Chinstrap      Dream            55.8           19.8   
340         341  Chinstrap      Dream            43.5           18.1   
341         342  Chinstrap      Dream            49.6           18.2   
342         343  Chinstrap      Dream            50.8           19.0   
343         344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[344 rows x 9 columns]

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


In [81]:
import numpy as np
df.isna().sum()

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [83]:
droped=df.dropna()
droped

Unnamed: 0    species     island  bill_length_mm  bill_depth_mm  \
0             1     Adelie  Torgersen            39.1           18.7   
1             2     Adelie  Torgersen            39.5           17.4   
2             3     Adelie  Torgersen            40.3           18.0   
4             5     Adelie  Torgersen            36.7           19.3   
5             6     Adelie  Torgersen            39.3           20.6   
..          ...        ...        ...             ...            ...   
339         340  Chinstrap      Dream            55.8           19.8   
340         341  Chinstrap      Dream            43.5           18.1   
341         342  Chinstrap      Dream            49.6           18.2   
342         343  Chinstrap      Dream            50.8           19.0   
343         344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
4                193.0       3450.0  female  2007  
5                190.0       3650.0    male  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[333 rows x 9 columns]

In [84]:
species_encoder=le.fit_transform(droped["species"])
species_encoder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [87]:
island_encoder=le.fit_transform(droped["island"])
s_encoder=le.fit_transform(droped["sex"])

In [92]:
feature=list(zip(species_encoder,island_encoder))
x_train,x_test,y_train,y_test=train_test_split(feature,s_encoder,test_size=0.3)

knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("Accuracy :",metrics.accuracy_score(y_test,y_pred))

Accuracy : 0.54
