In [3]:
import numpy as np

In [4]:
nums=np.array([1,2,3,4,5])
num=nums+2
print(num)

[3 4 5 6 7]


In [5]:
num2=np.array([[1,2,3],[4,8,9],[6,4,3]])
num3=np.array([[1,2,3],[4,8,9],[6,4,3]])
num4=num2*num3
print(num4)

[[ 1  4  9]
 [16 64 81]
 [36 16  9]]


In [6]:
n=np.arange(1,20)
print (n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
zeros=np.zeros((10,10))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
o=np.ones((10,10))
print(o)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
idp=np.eye(4)
print(idp)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
lin=np.linspace(1,10,15)
print(lin)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [11]:
r=np.random.rand(2,3)
print(r)

[[0.36949789 0.66398135 0.80507458]
 [0.03463149 0.11969225 0.63850481]]


In [12]:
r1=np.random.randint(50,100,5)
print(r1)

[91 56 54 64 97]


In [13]:
n=np.arange(1,17)
n1=n.reshape(4,4)
print (n1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
nu1=np.array([[1,2,3],[4,8,9],[6,4,3]])
nx=nu1.flatten()
print (nx)

[1 2 3 4 8 9 6 4 3]


In [15]:
rx= np.random.randint(5,100,5)
xmin = rx.min()
xmax=rx.max()
xar=rx.argmax()
print(xmin)
print(xmax)
print(xar)

29
68
2


In [16]:
nums2=nums[0:5]
print(nums2)

[1 2 3 4 5]


In [17]:
nums2d=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(nums2d)
print("\n")
print(nums2d.flatten())
print("\n")
print(nums2d[:3,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3 4 5 6 7 8 9]


[[1 2]
 [4 5]
 [7 8]]


In [38]:
idp= np.eye(8)
print(idp)
print("\n")
print(idp.flatten())
print("\n")
print(idp.reshape(16,4))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [46]:
rx= np.random.randint(1,100,10)
print(rx)
xmax=rx.max()
xar=rx.argmax()

print(xmax)
print(xar)

[64 59 94 81  7  2 45 69 73 70]
94
2
