In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [72]:
df=pd.read_csv("Iris.csv")
print(df.shape)
df.head()
Le=LabelEncoder()
Le.fit(df['Species'])
df.Species=Le.transform(df.Species)
df.drop('Id',axis=1,inplace=True)

(150, 6)


In [73]:
target_column=['Species']
predictors=list(set(list(df.columns))-set((target_column)))
df[predictors]=df[predictors]/df[predictors].max()



In [74]:
x=df[predictors].values
y=df[target_column].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


In [75]:
mlp=MLPClassifier(hidden_layer_sizes=(8,8,8),
activation='relu',solver='adam',max_iter=500)
mlp.fit(x_train,y_train)
predict_train=mlp.predict(x_train)
predict_test=mlp.predict(x_test)

C:\Users\CSE\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CSE\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [76]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))


[[37  0  0]
 [ 0 31  3]
 [ 0  1 40]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.91      0.94        34
           2       0.93      0.98      0.95        41

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.96      0.96      0.96       112



In [77]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

