In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt


In [5]:
df=pd.read_csv('Lab6_Social_Network_Ads.csv')
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [29]:
x=df.iloc[:,:-1].values
y=df.iloc[:,1].values



In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=42)

In [33]:
x_test

array([[    46,  22000],
       [    59,  88000],
       [    28,  44000],
       [    48,  96000],
       [    29,  28000],
       [    30,  62000],
       [    47, 107000],
       [    29,  83000],
       [    40,  75000],
       [    42,  65000],
       [    35,  65000],
       [    53,  34000],
       [    23,  48000],
       [    20,  23000],
       [    30,  87000],
       [    35, 108000],
       [    52,  38000],
       [    46,  74000],
       [    39,  42000],
       [    56,  60000],
       [    22,  27000],
       [    29,  80000],
       [    47,  23000],
       [    59,  76000],
       [    19,  19000],
       [    51,  23000],
       [    42,  80000],
       [    37,  53000],
       [    55, 125000],
       [    19,  21000],
       [    46,  41000],
       [    19,  70000],
       [    36, 144000],
       [    28,  79000],
       [    40, 107000],
       [    35,  75000],
       [    37,  55000],
       [    38,  65000],
       [    26,  30000],
       [    18,  68000],


In [35]:
y_test

array([ 22000,  88000,  44000,  96000,  28000,  62000, 107000,  83000,
        75000,  65000,  65000,  34000,  48000,  23000,  87000, 108000,
        38000,  74000,  42000,  60000,  27000,  80000,  23000,  76000,
        19000,  23000,  80000,  53000, 125000,  21000,  41000,  70000,
       144000,  79000, 107000,  75000,  55000,  65000,  30000,  68000,
        33000,  55000,  52000,  20000,  49000, 139000,  61000,  71000,
        41000,  43000,  79000,  82000,  55000,  80000,  80000,  31000,
       102000, 118000,  74000,  76000,  51000,  57000,  90000,  87000,
        59000, 137000,  90000, 144000,  59000, 113000, 138000,  85000,
        58000,  20000,  34000,  50000, 133000,  26000,  47000,  78000,
        57000,  28000, 134000,  39000,  26000, 120000,  52000,  74000,
        86000,  81000,  86000,  54000,  59000,  80000,  16000,  79000,
       130000,  64000, 143000, 112000, 122000,  71000,  25000,  19000,
        50000, 150000,  29000, 107000,  34000,  61000,  31000,  71000,
      

In [17]:
from sklearn import svm

elf=svm.SVC(kernel='linear')
elf.fit(x_train,y_train)
y_pred=elf.predict(x_test)

In [23]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))



Accuracy: 0.8916666666666667


In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [39]:
y_pred=knn.predict(x_test)
y_pred

array([ 22000,  88000,  44000,  96000,  28000,  63000, 108000,  83000,
        75000,  65000,  65000,  33000,  47000,  23000,  87000, 108000,
        38000,  74000,  42000,  60000,  27000,  80000,  23000,  75000,
        18000,  23000,  80000,  52000, 122000,  22000,  42000,  70000,
       144000,  79000, 108000,  75000,  55000,  65000,  30000,  66000,
        33000,  55000,  52000,  20000,  50000, 141000,  61000,  71000,
        42000,  43000,  79000,  82000,  55000,  80000,  80000,  32000,
       104000, 117000,  74000,  75000,  51000,  57000,  90000,  87000,
        59000, 135000,  90000, 144000,  59000, 113000, 141000,  84000,
        58000,  20000,  33000,  50000, 134000,  25000,  47000,  77000,
        57000,  28000, 134000,  38000,  25000, 118000,  52000,  74000,
        86000,  82000,  86000,  53000,  59000,  80000,  15000,  79000,
       131000,  65000, 144000, 113000, 118000,  71000,  25000,  18000,
        50000, 149000,  28000, 108000,  33000,  61000,  32000,  71000,
      

In [41]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.6
